### ISSUE TITLE
OmsCarver outRaster comes out flat

### ISSUE THREAD

**Issue by KimmoHop** [TheHortonMachine/hortonmachine#39]
In org.hortonmachine.gears.modules.r.carver.OmsCarver, WritableRaster outWR is initialized using value Double.NaN.
Later in loop, existing value of each pixel is read from outWR (Double.NaN) and checked with HMConstants.isNovalue() (compares to HMConstants.doubleNovalue -9999.0), so outWR is never updated.

Since the outWR is created locally, the comparison should not be necessary at all.

**Comment by moovida** [comment]
Thanks for reporting this. It was indeed a bit messy. I cleanedit up a bit and committed the change. A pity it didn't get in the 0.9.0 release done this morning.
