### ISSUE TITLE
Lakes detection removes upstream basins of the lake's downstream basin in the geoframeInputBuilder

### ISSUE THREAD

**Issue by martindoublem** [TheHortonMachine/hortonmachine#68]
In a case where the basin downstream of a lake where to contain more than one upstream basin (meaning more basins than the one containing the lake, in the case there is a confluence in the basin downstream of the lake), the basins upstream are not analyzed and included in the new topology file for the GEOframe input builder

The error seems to come from these lines:
https://github.com/TheHortonMachine/hortonmachine/blob/83f980452009ebfdc1ec83767a08d0c5847358ce/modules/src/main/java/org/hortonmachine/modules/GeoframeInputsBuilder.java#L336-L337

It can be seen clearly that the upstream basins are cleared and then the lake basin is added however the other upstream basins are not added again and are therefore ignored from the rest of the analysis. In the case of another lake being upstream, it seems that the lake is not aggregated, and does not cut the basins it is located in.

Example screenshots:
![screen](https://user-images.githubusercontent.com/42241431/135891692-6f4f46fa-fdec-4e3c-92a5-d8075e8c4a24.png)

Example files:
[D_basin_issue.zip](https://github.com/TheHortonMachine/hortonmachine/files/7279824/D_basin_issue.zip)

As it can be seen in topology and on the map, the basin numbered 391 and 336 in yellow are upstream of the basin number 433, which is itself downstream of the lake (in red). However they (391 and 336) and their upstream basins are excluded from the topology_lakes file (on the left).

It does seem however that the GEOframe input folder were built and populated correctly (in my small example).

**Comment by moovida** [comment]
Hi @martindoublem , thanks for this very good bug report. I will look into it using your testcase data.

**Comment by moovida** [comment]
Hi @martindoublem , I think it is fixed. I placed you a result folder in the following archive:
[geoframe.zip](https://github.com/TheHortonMachine/hortonmachine/files/7300229/geoframe.zip)

Could you please check the topology and the results in general to make sure I didn't miss anything?

**Comment by moovida** [comment]
Outch, sorry, I thought the topology file was in the zip. Attaching it here.

[tp_lakes.txt](https://github.com/TheHortonMachine/hortonmachine/files/7300741/tp_lakes.txt)

**Comment by martindoublem** [comment]
> Ok, do you need a build or just the commit of the fix?

A build, please, if you don't mind.

**Comment by martindoublem** [comment]
Hi there, would it possible to release the new version of the horton machine that solved this in the releases download package page?

A colleague of mine had the same issue as me today and I could not find a valid download link for the version that corrected this.

Thank you!

**Comment by moovida** [comment]
We are waiting to include the kriging part we are working on in a future official release. I am not sure: do you need an official release to work with the maven artifacts or do you just need a build?

**Comment by martindoublem** [comment]
No worries then. I have the build you gave me a while back already. Just
wanted to point it out that it was not available yet.
